[package]
name = "ctfjx_common"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
dotenvy = { workspace = true }
thiserror = { workspace = true }
validator = { workspace = true }
tracing = { workspace = true }
