name: Run Tests

on:
  push:
    branches:
      - main
      - v*
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  changed-files:
    name: Changed Files
    runs-on: ubuntu-latest
    outputs:
      test-source: ${{ steps.changed-files.outputs.test-source_any_modified == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 50 # Assume PRs are less than 50 commits

      - name: Find changed files
        uses: tj-actions/changed-files@v47
        id: changed-files
        with:
          files_yaml: |
            common: &common
              - .github/workflows/test-worker.yml
              - Makefile

            test-source:
              - *common
              - crates/**
              - Cargo.lock
              - Cargo.toml

  source:
    name: Test CTFjx
    runs-on: ubuntu-latest
    needs: changed-files
    if: needs.changed-files.outputs.test-source == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Caching dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: rust-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml', '**/Cargo.lock') }}
          restore-keys: |
            rust-${{ runner.os }}

      - name: Setup Rust
        run: |
          rustup show active-toolchain || (rustup update)

      - name: Get protoc version
        id: protoc_version
        run: echo "version=$(apt-cache show protobuf-compiler | grep -m1 'Version' | awk '{print $2}')" >> $GITHUB_ENV

      - name: Cache protoc
        uses: actions/cache@v5
        with:
          path: /usr/bin/protoc
          key: protoc-${{ runner.os }}-${{ env.version }}

      - name: Install protoc
        run: |
          if ! command -v protoc &> /dev/null; then
            sudo apt-get install -y protobuf-compiler
          fi

      - name: Test
        run: |
          make test

      - name: Lint
        run: |
          make lint/ci

      - name: Format
        run: |
          make fmt/ci

      - name: Security
        continue-on-error: true
        run: |
          make security

  check:
    if: always()
    name: Tests Successful
    runs-on: ubuntu-latest
    needs: [source]

    steps:
      - name: Whether the whole test suite passed
        uses: re-actors/alls-green@v1.2.2
        with:
          allowed-skips: ${{ toJSON(needs) }}
          jobs: ${{ toJSON(needs) }}
